# Generated by Django 3.2.15 on 2022-09-18 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationvote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informationvote_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AddField(
            model_name='informationvote',
            name='information',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.information'),
        ),
        migrations.AddField(
            model_name='informationvote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informationvote_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AddField(
            model_name='informationvote',
            name='voter',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voter+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='informationvote',
            constraint=models.UniqueConstraint(fields=('information', 'voter'), name='Only one vote per user on each information'),
        ),
    ]
