# Generated by Django 3.2.15 on 2022-08-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationinformation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='api.location', verbose_name='Location which holds the information'),
        ),
        migrations.AlterField(
            model_name='locationtrackgauge',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_gauges', to='api.location', verbose_name='Location which has the track gauge'),
        ),
    ]
