# Generated by Django 3.2.15 on 2022-09-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationVote',
        ),
    ]
