
class RouteNames:
    ROUTE_BILLET = 'api.billet'
    ROUTE_BILLET_GATEWAY = 'api.billet_gateway'
    ROUTE_BILLET_RENEW = 'api.billet.renew'
    ROUTE_BILLET_UPDATE = 'api.billet.update'
    ROUTE_DOC_OPENAPI = 'api.docs.openapi'
    ROUTE_DOC_REDOC = 'api.docs.redoc'
    ROUTE_DOC_SWAGGER = 'api.docs.swagger'
    ROUTE_EVENT = 'api.event'
    ROUTE_EVENT_FILE = 'api.event.file'
    ROUTE_EVENT_FILE_DOWNLOAD = 'api.event.file.download'
    ROUTE_EVENT_LINK = 'api.event.link'
    ROUTE_EVENT_SUBSCRIPTION = 'api.event.subscription'
    ROUTE_EVENT_VACANCY = 'api.event.vacancy'
    ROUTE_EVENT_VACANCY_SUBSCRIBE = 'api.event.vacancy.subscribe'
    ROUTE_LOGIN = 'api.login'
    ROUTE_ME = 'api.me'
    ROUTE_REGISTER = 'api.register'
    ROUTE_STATE = 'api.state'
    ROUTE_STATE_CITY = 'api.state.city'
    ROUTE_SUBSCRIPTION = 'api.subscription'
    ROUTE_SUBSCRIPTION_BILLET = 'api.subscription.billet'
    ROUTE_SUBSCRIPTION_BILLET_DOWNLOAD = 'api.subscription.billet.download'
