# tblFerroviaVagaoSubTipo
#
# DESC:			Tabela de armazenamento dos subtipos dos vagões das ferrovias
# TODO:			-
# NOTES:		-
#
DROP TABLE IF EXISTS tblFerroviaVagaoSubTipo;
CREATE TABLE tblFerroviaVagaoSubTipo (
	CodFerroviaVagaoSubTipo		INT(8)			NOT NULL	AUTO_INCREMENT PRIMARY KEY 	COMMENT 'Código de indexação',
	CodFerroviaVagaoTipo 		INT(8)			NOT NULL								COMMENT 'Código do tipo que origina o subtipo',
	LetraVagaoSubTipo			VARCHAR(2)		NULL									COMMENT 'Conjunto de duas letras que formam o subtipo',
	DescricaoSubTipo			VARCHAR(255)	NULL									COMMENT 'Descrição do subtipo de vagão',
	Ativo 						BOOLEAN			NOT NULL	DEFAULT TRUE 				COMMENT 'Se o registro está ativo'
) Engine = MyISAM 	DEFAULT CHARSET = utf8mb4	COMMENT = 'Tabela de armazenamento dos tipos dos vagões das ferrovias';

INSERT INTO tblFerroviaVagaoSubTipo (CodFerroviaVagaoSubTipo, CodFerroviaVagaoTipo, LetraVagaoSubTipo, DescricaoSubTipo, Ativo) VALUES
	(1, 1, 'AC', 'Gaiola com cobertura, estrado e estrutura metálica (inclui réguas de madeira)', 1),
	(2, 1, 'AM', 'Gaiola com cobertura, de madeira', 1),
	(3, 1, 'AN', 'Gaiola de serviço não-remunerado', 1),
	(4, 1, 'AR', 'Gaiola para animais de raça', 1),
	(5, 1, 'AV', 'Gaiola para aves', 1),
	(6, 1, 'AD', 'Gaiola descoberta', 1),
	(7, 1, 'AQ', 'Gaiola - Outros tipos', 1),
	(8, 2, 'CC', 'Caboose convencional', 1),
	(9, 2, 'CB', 'Caboose com compartimento para bagagens', 1),
	(10, 2, 'CN', 'Caboose de serviço não-remunerado', 1),
	(11, 2, 'CQ', 'Caboose - Outros tipos', 1),
	(12, 3, 'FR', 'Fechado convencional - Caixa metálica com revestimento', 1),
	(13, 3, 'FS', 'Fechado convencional - Caixa metálica sem revestimento', 1),
	(14, 3, 'FM', 'Fechado convencional - Caixa de madeira ou mista', 1),
	(15, 3, 'FN', 'Fechado de serviço não-remunerado', 1),
	(16, 3, 'FE', 'Fechado com escotilhas', 1),
	(17, 3, 'FH', 'Fechado com escotilhas - Fundo em lombo de camelo ou Tremonhas (Hopper)', 1),
	(18, 3, 'FB', 'Fechado com escotilhas - Portas basculantes - Fundo em lombo de camelo', 1),
	(19, 3, 'FP', 'Fechado com escotilhas - Portas basculantes - Fundo em lombo de camelo - Proteção anti-corrosiva', 1),
	(20, 3, 'FL', 'Fechado com laterais corrediças (all door)', 1),
	(21, 3, 'FV', 'Fechado ventilado', 1),
	(22, 3, 'FQ', 'Fechado - Outros tipos', 1),
	(23, 4, 'GD','Gôndola para descarga em virador (car dumper)', 1),
	(24, 4, 'GP','Gôndola de bordas fixas e portas laterais', 1),
	(25, 4, 'GF','Gôndola de bordas fixas e fundo móvel (drop-bottom)', 1),
	(26, 4, 'GM','Gôndola de bordas fixas e cobertura móvel', 1),
	(27, 4, 'GN','Gôndola de serviço não-remunerado', 1),
	(28, 4, 'GT','Gôndola de bordas tombantes', 1),
	(29, 4, 'GS','Gôndola de semi-bordas tombantes', 1),
	(30, 4, 'GH','Gôndola de bordas basculantes ou semi-tombantes - Fundo em lombo de camelo', 1),
	(31, 4, 'GC','Gôndola de bordas basculantes ou semi-tombantes - Fundo em lombo de camelo - Cobertura móvel', 1),
	(32, 4, 'GB','Gôndola basculante', 1),
	(33, 4, 'GQ','Gôndola - Outros tipos', 1),
	(34, 5, 'HF','Hopper fechado convencional', 1),
	(35, 5, 'HP','Hopper fechado com proteção anti-corrosiva', 1),
	(36, 5, 'HE','Hopper tanque (center-flow) com proteção anti-corrosiva', 1),
	(37, 5, 'HT','Hopper tanque (center-flow) convencional', 1),
	(38, 5, 'HN','Hooper de serviço não-remunerado', 1),
	(39, 5, 'HA','Hopper aberto', 1),
	(40, 5, 'HQ','Hopper - Outros tipos', 1),
	(41, 6, 'IC','Isotérmico convencional', 1),
	(42, 6, 'IF','Isotérmico frigorífico', 1),
	(43, 6, 'IN','Isotérmico de serviço não-remunerado', 1),
	(44, 6, 'IQ','Isotérmico - Outros tipos', 1),
	(45, 7, 'PM','Plataforma convencional com piso de madeira', 1),
	(46, 7, 'PE','Plataforma convencional com piso metálico', 1),
	(47, 7, 'PD','Plataforma convencional com dispositivo para containers', 1),
	(48, 7, 'PC','Plataforma para containers', 1),
	(49, 7, 'PR','Plataforma com estrado rebaixado', 1),
	(50, 7, 'PN','Plataforma de serviço não-remunerado', 1),
	(51, 7, 'PT','Plataforma para auto-trem', 1),
	(52, 7, 'PG','Plataforma para piggy-back', 1),
	(53, 7, 'PP','Plataforma com cabeceira (bulkhead)', 1),
	(54, 7, 'PB','Plataforma para bobinas', 1),
	(55, 7, 'PA','Plataforma com 2 pavimentos para automóveis', 1),
	(56, 7, 'PQ','Plataforma - Outros tipos', 1),
	(57, 8, 'QQ','Qualquer - Qualquer (Outros tipos)', 1),
	(58, 8, 'QN','Qualquer de serviço não-remunerado', 1),
	(59, 9, 'TC','Tanque convencional', 1),
	(60, 9, 'TS','Tanque com serpentinas para aquecimento', 1),
	(61, 9, 'TP','Tanque para produtos pulverulentos (em pó)', 1),
	(62, 9, 'TF','Tanque para fertilizantes', 1),
	(63, 9, 'TN','Tanque de serviço não-remunerado', 1),
	(64, 9, 'TA','Tanque para cidos ou outros líquidos corrosivos', 1),
	(65, 9, 'TG','Tanque para gás liquefeito de petróleo', 1),
	(66, 9, 'TQ','Tanque - Outros tipos', 1);