version: '3'

services:
  infotrem-django:
    container_name: infotrem-api
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code/
    ports:
      - "5000:5000"
    expose:
      - 5000

  infotrem-node:
    container_name: infotrem-app
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/code/app:delegated
    ports:
      - "3000:3000"
    expose:
      - 3000

networks:
  default:
    name: nginx-proxy
    external: true
