version: '3'

services:
  infotrem-django:
    container_name: infotrem-api
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code/
    expose:
      - 5000

  infotrem-node:
    container_name: infotrem-app
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/app:/code/app:delegated
    expose:
      - 3000

networks:
  default:
    external:
      name: nginx-proxy
