from api.views.cronjob.cronjob_view import CronJobView
from api.views.doc.doc_view import SchemaView
from api.views.email_validation.email_validation_check_view import EmailValidationCheckView
from api.views.email_validation.email_validation_resend_view import EmailValidationResendView
from api.views.health.health_view import HealthViewSet
from api.views.location.location_city_view import LocationCityViewSet
from api.views.location.location_state_view import LocationStateViewSet
from api.views.me.me_view import MeView
from api.views.user.user_view import UserViewSet
