from typing import List, Dict, Optional

from infotrem.models.location import TrackGaugeConfiguration
from infotrem.models.railroad import Manufacturer
from infotrem.models.rolling_stock import RollingStock
from infotrem.models.rolling_stock_locomotive import RollingStockLocomotiveModel


def parse_prime_mover_type(prime_mover: str) -> Optional[str]:
    map_dict = {
        "DIESEL_ELECTRIC": RollingStock.RollingStockPrimeMover.DIESEL_ELECTRIC,
        "ELECTRIC": RollingStock.RollingStockPrimeMover.ELECTRIC,
    }
    return map_dict[prime_mover] if prime_mover in map_dict else None


def create_single_locomotive(loco: Dict):
    RollingStockLocomotiveModel.objects.create(
        wikipedia_url=loco['wikipedia_url'],
        name=loco['name'],

        adhesion_factor=loco['adhesion_factor'] if 'adhesion_factor' in loco else None,
        allow_multiple_units=loco['allow_multiple_units'] if 'allow_multiple_units' in loco else None,
        brake_system=loco['brake_system'] if 'brake_system' in loco else None,
        cooling_fluid_capacity=loco['cooling_fluid_capacity'] if 'cooling_fluid_capacity' in loco else None,
        cylinders_size=loco['cylinders_size'] if 'cylinders_size' in loco else None,
        first_unit_year=loco['first_unit_year'] if 'first_unit_year' in loco else None,
        fuel_capacity=loco['fuel_capacity'] if 'fuel_capacity' in loco else None,
        gauge=TrackGaugeConfiguration.objects.get(name=loco['gauge']) if 'gauge' in loco else None,
        generator=loco['generator'] if 'generator' in loco else None,
        height=loco['height'] if 'height' in loco else None,
        horsepower_available=loco['horsepower_available'] if 'horsepower_available' in loco else None,
        horsepower_total=loco['horsepower_total'] if 'horsepower_total' in loco else None,
        length=loco['length'] if 'length' in loco else None,
        lubricant_oil_capacity=loco['lubricant_oil_capacity'] if 'lubricant_oil_capacity' in loco else None,
        manufacturer=Manufacturer.objects.get(short_name=loco['manufacturer']) if 'manufacturer' in loco else None,
        minimum_track_radius=loco['minimum_track_radius'] if 'minimum_track_radius' in loco else None,
        motor_builder=loco['motor_builder'] if 'motor_builder' in loco else None,
        motor_capacity=loco['motor_capacity'] if 'motor_capacity' in loco else None,
        motor_type=loco['motor_type'] if 'motor_type' in loco else None,
        nickname=loco['nickname'] if 'nickname' in loco else None,
        primary_motor=loco['primary_motor'] if 'primary_motor' in loco else None,
        prime_mover=parse_prime_mover_type(loco['prime_mover_type'] if 'prime_mover_type' in loco else None),
        rpm_limit=loco['rpm_limit'] if 'rpm_limit' in loco else None,
        sand_capacity=loco['sand_capacity'] if 'sand_capacity' in loco else None,
        serial_number_range=loco['serial_number_range'] if 'serial_number_range' in loco else None,
        traction_effort=loco['traction_effort'] if 'traction_effort' in loco else None,
        traction_motor=loco['traction_effort'] if 'traction_effort' in loco else None,
        truck_type=loco['truck_type'] if 'truck_type' in loco else None,
        velocity_max=loco['velocity_max'] if 'velocity_max' in loco else None,
        velocity_min=loco['velocity_min'] if 'velocity_min' in loco else None,
        weight=loco['weight'] if 'weight' in loco else None,
        weight_adherent=loco['weight_adherent'] if 'weight_adherent' in loco else None,
        weight_per_axle=loco['weight_per_axle'] if 'weight_per_axle' in loco else None,
        wheel_arrangement_aar=loco['wheel_arrangement_aar'] if 'wheel_arrangement_aar' in loco else None,
        wheel_arrangement_whyte=loco['wheel_arrangement_whyte'] if 'wheel_arrangement_whyte' in loco else None,
        wheel_diameter=loco['wheel_diameter'] if 'wheel_diameter' in loco else None,
        wheelbase=loco['wheelbase'] if 'wheelbase' in loco else None,
        width=loco['width'] if 'width' in loco else None,
    )


def create_locomotives(parsed_list: List):
    for locomotive in parsed_list:
        create_single_locomotive(locomotive)


def run():
    create_locomotives([
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/ALCO_FA-1",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "ALCO",
            "name": "DL212",
            "first_unit_year": 1948,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
            "wheel_diameter": 1016.0000,
            "wheelbase": 8280.0000,
            "length": 15697.0000,
            "width": 2330.0000,
            "height": 4503.0000,
            "weight": 108200.0000,
            "weight_per_axle": 27050.0000,
            "weight_adherent": 108200.0000,
            "fuel_capacity": "4540 L",
            "motor_builder": "ALCO",
            "primary_motor": "ALCO 244",
            "generator": "GE 564 C1",
            "traction_motors": "GE 752 E1",
            "cylinders_size": "230,2 mm (9 1/16 in) x 266,7 mm (10 1/2 in)",
            "allow_multiple_units": True,
            "velocity_max": 104.0000,
            "horsepower_available": 1500,
            "minimum_track_radius": 84000,
            "brake_system": "24RL",
            "nickname": "Biriba",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/ALCO_PA-2",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "ALCO",
            "name": "PA-2 (DL-304D)",
            "first_unit_year": 1953,
            "aar_wheel_arrangement": "A1A-A1A",
            "gauge": "Larga",
            "motor_builder": "ALCO",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/ALCO_RS-3",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "ALCO",
            "name": "RS-3 (E1662)",
            "first_unit_year": 1952,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
            "wheel_diameter": 1016.0000,
            "wheelbase": 2.0000,
            "length": 18.0000,
            "height": 4.0000,
            "weight": 109.9600,
            "weight_per_axle": 27.4900,
            "weight_adherent": 109.9600,
            "motor_builder": "ALCO",
            "motor_type": "ALCO 244",
            "generator": "GE GT-581",
            "cylinders_size": "230,2 mm (9 1/16 in) x 266,7 mm (10 1/2 in)",
            "allow_multiple_units": True,
            "velocity_max": 105.0000,
            "horsepower_available": 1500,
            "traction_effort": 23,
            "minimum_track_radius": 45120,
            "nickname": "Canadenses e Rabo Quente",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/ALCO_RSC-1",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "ALCO",
            "name": "RSC-1 (E1647)[1]",
            "first_unit_year": 1946,
            "aar_wheel_arrangement": "A1A-A1A",
            "gauge": "Larga",
            "motor_builder": "ALCO",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/ALCO_RSC-3",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "ALCO",
            "name": "E1662",
            "aar_wheel_arrangement": "A1A-A1A",
            "gauge": "Larga",
            "fuel_capacity": "3028 L",
            "motor_builder": "ALCo",
            "primary_motor": "ALCo 244",
            "motor_type": "V-12",
            "velocity_max": 105.0000,
            "sigo_numeric_range": "6551-6562",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/ALCO_RSD-8",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "ALCO",
            "name": "RSD-8 (DL-531)[2]",
            "first_unit_year": 1958,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "C-C",
            "weight": 62000.0000,
            "motor_builder": "ALCO",
            "allow_multiple_units": True,
            "horsepower_total": 900,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/Baldwin_AS616E",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "Baldwin-Whitcomb",
            "name": "AS616 e AS616E",
            "first_unit_year": 1952,
            "aar_wheel_arrangement": "C-C",
            "trucks_type": "AS616: Trimount Type Normal AS616E: Trimount Type & Floating Bolster",
            "wheel_diameter": 1067.0000,
            "length": 17.0000,
            "width": 2.0000,
            "motor_builder": "Baldwin Locomotive Works",
            "primary_motor": "Baldwin 608A",
            "rpm_limit": 1,
            "motor_type": "Turbo - Alimentado",
            "generator": "Westinghouse 471 BZ",
            "traction_motors": "6x Westinghouse AS616: 563A AS616E: 370 DEZ",
            "cylinders_size": "323,85 mm (12 3/4 in) x 393,70 mm (15 1/2 in)",
            "allow_multiple_units": True,
            "velocity_max": 65.0000,
            "horsepower_total": 1650,
            "horsepower_available": 1600,
            "brake_system": "6SL",
            "nickname": "Baldwin, Papo Amarelo",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/Baldwin-Westinghouse_1-B%2BB-1",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "Baldwin-Westinghouse",
            "first_unit_year": 1921,
            "aar_wheel_arrangement": "1-B+B-1",
            "gauge": "Larga",
            "wheel_diameter": 1600.0000,
            "length": 16129.0000,
            "height": 3834.0000,
            "weight": 128000.0000,
            "weight_per_axle": 21300.0000,
            "weight_adherent": 93440.0000,
            "allow_multiple_units": True,
            "velocity_max": 105.0000,
            "horsepower_total": 1800,
            "horsepower_available": 1627,
            "sigo_numeric_range": "6311 - 6313",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/Baldwin-Westinghouse_C%2BC",
            "name": "Baldwin-Westinghouse C+C",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "Baldwin-Westinghouse",
            "first_unit_year": 1921,
            "aar_wheel_arrangement": "C+C",
            "gauge": "Larga",
            "wheel_diameter": 1016.0000,
            "length": 15291.0000,
            "height": 3834.0000,
            "weight": 106000.0000,
            "weight_per_axle": 17700.0000,
            "allow_multiple_units": True,
            "velocity_max": 65.0000,
            "horsepower_total": 1350,
            "sigo_numeric_range": "6411 - 6418",
            "nickname": "Cristaleira",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EE_VFFLB",
            "name": "EE VFFLB",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "English-Electric",
            "first_unit_year": 1938,
            "aar_wheel_arrangement": "1-B-B-1",
            "gauge": "Métrica",
            "width": 2670.0000,
            "height": 3730.0000,
            "weight": 54500.0000,
            "weight_per_axle": 10000.0000,
            "weight_adherent": 38500.0000,
            "motor_builder": "English Electric",
            "primary_motor": "EE 8K",
            "motor_type": "Aspirado",
            "velocity_max": 75.5000,
            "horsepower_total": 450,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EE_RFN",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "English-Electric",
            "name": "LD453",
            "first_unit_year": 1954,
            "aar_wheel_arrangement": "A1A-A1A",
            "gauge": "Métrica",
            "trucks_type": "Chapas rebitadas",
            "wheel_diameter": 940.0000,
            "wheelbase": 1.0000,
            "length": 15.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 72.7680,
            "weight_adherent": 49.4550,
            "fuel_capacity": "2160 L",
            "motor_builder": "English Eletric",
            "primary_motor": "8SRKT",
            "rpm_limit": 850,
            "motor_type": "8 cilindros em linha, superalimentado, 4 tempos",
            "cylinders_size": "254,0 mm (10 in) x 304,8 mm (12 in)",
            "allow_multiple_units": True,
            "velocity_max": 100.0000,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 80000,
            "sigo_numeric_range": "701-713",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EE_EFSJ",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "English-Electric",
            "first_unit_year": 1949,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "wheel_diameter": 1219.0000,
            "wheelbase": 10.0000,
            "length": 20.0000,
            "width": 2.0000,
            "height": 4.0000,
            "weight": 127.1700,
            "weight_per_axle": 21.1950,
            "rpm_limit": 1,
            "traction_motors": "EE-514-A",
            "velocity_max": 100.0000,
            "horsepower_total": 3000,
            "minimum_track_radius": 160000,
            "nickname": "Pimentinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMAQ_MX620",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMAC",
            "name": "MX620[1]",
            "first_unit_year": 1980,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "C-C",
            "motor_builder": "Bombardier",
            "primary_motor": "251",
            "horsepower_total": 2200,
            "horsepower_available": 2000,
            "sigo_numeric_range": "6101-6174",
            "nickname": "MX",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_B12",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "B12",
            "first_unit_year": 1953,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Flexcoil",
            "wheel_diameter": 1016.0000,
            "wheelbase": 2.0000,
            "length": 13.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 68.0000,
            "weight_per_axle": 17.0000,
            "weight_adherent": 68.0000,
            "fuel_capacity": "4540 L",
            "lubricant_oil_capacity": 625,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "EMD 12-567B",
            "rpm_limit": 800,
            "motor_type": "Combustão interna",
            "motor_capacity": "9.290cc³ x 12",
            "generator": "D15-E",
            "traction_motors": "D19",
            "cylinders_size": "215,9 mm (8 1/2 in) x 254,0mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 97.0000,
            "velocity_min": 16.0000,
            "horsepower_available": 1015,
            "traction_effort": 14,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 58820,
            "brake_system": "6SL",
            "sigo_numeric_range": "4091 a 4099",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_BB40-2",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "BB40-2",
            "aar_wheel_arrangement": "B+B-B+B",
            "length": 20980.0000,
            "width": 3127.0000,
            "height": 4753.0000,
            "fuel_capacity": "12000 L - 15000 L",
            "motor_builder": "EMD",
            "primary_motor": "EMD 16-645-E3",
            "traction_motors": "6 × General Motors D31",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_BB45-2",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "BB40-2",
            "aar_wheel_arrangement": "B+B-B+B",
            "length": 20980.0000,
            "width": 3127.0000,
            "height": 4753.0000,
            "fuel_capacity": "12000 L - 15000 L",
            "motor_builder": "EMD",
            "primary_motor": "EMD 16-645-E3",
            "traction_motors": "6 × General Motors D31",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_DDM45",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "DDM45",
            "first_unit_year": 1970,
            "aar_wheel_arrangement": "D-D",
            "gauge": "Métrica",
            "trucks_type": "Flexcoil D",
            "wheel_diameter": 1016.0000,
            "length": 22.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 162.0000,
            "weight_per_axle": 20.2500,
            "weight_adherent": 162.0000,
            "fuel_capacity": "10333 L",
            "motor_builder": "EMD",
            "primary_motor": "EMD 20-645E3 Turbo",
            "rpm_limit": 900,
            "motor_type": "20 cilindros em “V”",
            "motor_capacity": "10.560cc³ x 20",
            "generator": "AR-10B3",
            "traction_motors": "D-29",
            "cylinders_size": "230,2 mm (9 1/16 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 84.9000,
            "velocity_min": 19.8000,
            "horsepower_total": 3900,
            "horsepower_available": 3600,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 83000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_G12",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "G12",
            "aar_wheel_arrangement": "Brasil: B-B; A1A-A1A Austrália: C-C",
            "trucks_type": "Brasil: Flexi-coil B (L-136), Flexi-coil A1A  Mundo: Flexi-coil C, Bloomberg",
            "wheel_diameter": 1016.0000,
            "length": 14.0000,
            "height": 3.0000,
            "lubricant_oil_capacity": 625,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "12-567C Modernizadas: 12-645E",
            "motor_type": "12 cilindros em V Aspirado",
            "generator": "D12F / D32F",
            "traction_motors": "Bitola 1.000mm: D19 e D29  Modernizadas: D31  Bitola 1.600mm: D47B",
            "cylinders_size": "215,9 mm (8 1/2 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_min": 18.0000,
            "horsepower_total": 1425,
            "horsepower_available": 1310,
            "minimum_track_radius": 58820,
            "brake_system": "6SL/26L",
            "sigo_numeric_range": "B-B RFFSA: (90)4101 a (90)4269  A1A RFFSA: (90)4281 a (90)4290Fepasa ex-CMEF: (91)3651 a(91)3680Fepasa ex-CPEF: (91)7051 a (91)7068",
            "nickname": "EMD: General Motors  GMDD: Canadenses",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_G16",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "G16U",
            "first_unit_year": 1963,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "weight_per_axle": 16.8000,
            "fuel_capacity": "4800 L",
            "primary_motor": "EMD 645E V16 (atual)",
            "traction_motors": "GM - D29",
            "velocity_max": 100.0000,
            "horsepower_total": 1950,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_G22CU",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "MACOSA",
            "name": "G22CU",
            "first_unit_year": 1970,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "Flexicoil C",
            "wheel_diameter": 1016.0000,
            "length": 15.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 92.0000,
            "weight_per_axle": 15.3330,
            "weight_adherent": 92.0000,
            "fuel_capacity": "4000 L",
            "lubricant_oil_capacity": 625,
            "cooling_fluid_capacity": 681,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "12-645E",
            "rpm_limit": 900,
            "motor_type": "12 cilindros em V  Aspirado",
            "motor_capacity": "10.560cc³ x 12",
            "generator": "D32T",
            "traction_motors": "D29 ou D31",
            "cylinders_size": "230,2 mm (9 1/16 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 97.0000,
            "velocity_min": 14.0000,
            "horsepower_total": 1650,
            "horsepower_available": 1500,
            "traction_effort": 21,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 59000,
            "brake_system": "26L",
            "sigo_numeric_range": "4451-4474",
            "nickname": "Gauxas",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_G22U",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "MACOSA",
            "name": "G22U",
            "first_unit_year": 1971,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Flexicoil B",
            "wheel_diameter": 1016.0000,
            "wheelbase": 2.0000,
            "length": 15.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 73.0000,
            "weight_per_axle": 18.2500,
            "weight_adherent": 73.0000,
            "fuel_capacity": "4000 L",
            "lubricant_oil_capacity": 625,
            "cooling_fluid_capacity": 681,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "12-645E",
            "rpm_limit": 900,
            "motor_type": "12 cilindros em V Aspirado",
            "motor_capacity": "10.560cc³ x 12",
            "generator": "D32T",
            "traction_motors": "D29 ou D31",
            "cylinders_size": "230,2 mm (9 1/16 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 97.0000,
            "velocity_min": 21.7000,
            "horsepower_total": 1650,
            "horsepower_available": 1500,
            "traction_effort": 15,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 59000,
            "brake_system": "26L",
            "sigo_numeric_range": "4301-4429",
            "nickname": "Macosas",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_G26CU",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "G26CU",
            "first_unit_year": 1974,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "Flexicoil GC",
            "wheel_diameter": 1016.0000,
            "length": 17.0000,
            "width": 2.0000,
            "height": 3.0000,
            "lubricant_oil_capacity": 737,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "16-645E",
            "rpm_limit": 900,
            "motor_type": "16 cilindros em V  Aspirado",
            "motor_capacity": "10.560cc³ x 16",
            "generator": "D32T",
            "traction_motors": "D29  MP: D31",
            "cylinders_size": "230,2 mm (9 1/16 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "horsepower_total": 2200,
            "horsepower_available": 2000,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 85000,
            "brake_system": "26L/28-LAV-1",
            "sigo_numeric_range": "4501-4535  MP: 4507, 4509, 4511, 4515, 4516, 4521, 4524, 4525, 4529, 4531",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_G8",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "G8",
            "aar_wheel_arrangement": "B-B; A1A-A1A",
            "gauge": "Métrica",
            "trucks_type": "Flexi-coil B (L-136), Flexi-coil A1A",
            "wheel_diameter": 1016.0000,
            "length": 14.0000,
            "height": 3.0000,
            "lubricant_oil_capacity": 625,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "8-567C",
            "rpm_limit": 835,
            "motor_type": "8 cilindros em V Aspirado",
            "motor_capacity": "9.287cc³ x 8",
            "generator": "D12F",
            "traction_motors": "D19 e D29",
            "cylinders_size": "215,9 mm (8 1/2 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 100.0000,
            "velocity_min": 18.0000,
            "horsepower_total": 950,
            "horsepower_available": 875,
            "minimum_track_radius": 58820,
            "brake_system": "6SL",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GL8",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "GL8",
            "first_unit_year": 1960,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Flexicoil",
            "wheel_diameter": 1016.0000,
            "wheelbase": 2.0000,
            "length": 11.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 62.0000,
            "weight_per_axle": 15.5000,
            "weight_adherent": 62.0000,
            "fuel_capacity": "1893 L",
            "lubricant_oil_capacity": 492,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "EMD 8-567CR",
            "rpm_limit": 835,
            "motor_type": "Combustão interna",
            "motor_capacity": "9.290cc³ x 8",
            "generator": "D25-E",
            "traction_motors": "D-29",
            "cylinders_size": "215,9 mm (8 1/2 in) x 254,0mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 100.0000,
            "velocity_min": 16.0000,
            "horsepower_total": 950,
            "horsepower_available": 875,
            "traction_effort": 15,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 58820,
            "brake_system": "26LA",
            "sigo_numeric_range": "Série 4000 a 4050 ( RFFSA ) e 3600 a 3650 ( Fepasa )",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GP9",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "GP9L",
            "first_unit_year": 1954,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "length": 17120.0000,
            "width": 3124.0000,
            "height": 4420.0000,
            "weight": 112944.0000,
            "primary_motor": "EMD 567C V16",
            "traction_motors": "GM - D31",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GT18MC",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "GT18MC",
            "first_unit_year": 1974,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "SCAW - GLC",
            "wheel_diameter": 915.0000,
            "wheelbase": 9.0000,
            "length": 16.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 82.7200,
            "weight_per_axle": 13.7200,
            "fuel_capacity": "6000 L",
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "EMD 8-645 E3",
            "rpm_limit": 900,
            "motor_type": "8V - Turbo",
            "allow_multiple_units": True,
            "velocity_max": 100.0000,
            "velocity_min": 19.0000,
            "horsepower_available": 1450,
            "traction_effort": 20,
            "minimum_track_radius": 85000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GT22CUM-1",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "Villares",
            "name": "GT22CUM-1",
            "first_unit_year": 1982,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "HTC",
            "wheel_diameter": 1016.0000,
            "wheelbase": 9.0000,
            "length": 17.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 108.0000,
            "weight_per_axle": 18.0000,
            "fuel_capacity": "7000 L",
            "sand_capacity": 0.5100,
            "motor_builder": "EMD",
            "primary_motor": "EMD 12-645 E3B",
            "rpm_limit": 900,
            "motor_type": "Turbo Diesel / 12V",
            "allow_multiple_units": True,
            "velocity_max": 105.0000,
            "velocity_min": 20.0000,
            "horsepower_available": 2250,
            "traction_effort": 23,
            "minimum_track_radius": 71930,
            "sigo_numeric_range": "4601 a 4652",
            "nickname": "Villares",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GT22CUM-2",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "Villares",
            "name": "GT22CUM-2",
            "first_unit_year": 1986,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "HTC",
            "wheel_diameter": 1016.0000,
            "wheelbase": 9.0000,
            "length": 17.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 120.0000,
            "weight_per_axle": 20.0000,
            "fuel_capacity": "7000 L",
            "sand_capacity": 0.5100,
            "motor_builder": "EMD",
            "primary_motor": "EMD 12-645 E3B",
            "rpm_limit": 900,
            "motor_type": "12V - Turbo",
            "allow_multiple_units": True,
            "velocity_max": 80.0000,
            "velocity_min": 18.3000,
            "horsepower_available": 2250,
            "traction_effort": 28,
            "minimum_track_radius": 70000,
            "sigo_numeric_range": "4653 a 4662",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GT26CUM",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "Villares",
            "name": "GT26CU-2",
            "first_unit_year": 1972,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "Flexcoil C",
            "wheel_diameter": 1016.0000,
            "length": 20.0000,
            "width": 3.0000,
            "height": 4.0000,
            "fuel_capacity": "7360 L / 9462 L / 10870 L",
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "16-645E3",
            "rpm_limit": 900,
            "motor_type": "2 tempos,  16 cilindros em V(45º)  Turbo Alimentado",
            "motor_capacity": "10.560cc³ x 16",
            "generator": "AR-10-F",
            "traction_motors": "901 a 934: D29  935 a 940: D31",
            "cylinders_size": "230,2 mm (9 1/16 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_min": 20.0000,
            "adhesion_factor": 0.2500,
            "brake_system": "26L",
            "nickname": "GT  GT26",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_GT26MC",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "GT26MC",
            "first_unit_year": 1974,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "SCAW - GLC",
            "wheel_diameter": 915.0000,
            "wheelbase": 9.0000,
            "length": 19.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight_per_axle": 18.5830,
            "fuel_capacity": "6100 L",
            "lubricant_oil_capacity": 945,
            "cooling_fluid_capacity": 1045,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "EMD 16-645 E3",
            "rpm_limit": 900,
            "motor_type": "V16 - Turbo",
            "allow_multiple_units": True,
            "velocity_max": 100.0000,
            "velocity_min": 19.0000,
            "traction_effort": 27,
            "minimum_track_radius": 84000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_SD18",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "SD18",
            "first_unit_year": 1961,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "wheel_diameter": 1016.0000,
            "wheelbase": 2.0000,
            "length": 16.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 163.0100,
            "weight_per_axle": 27.1680,
            "weight_adherent": 163.0100,
            "motor_builder": "EMD",
            "primary_motor": "EMD 567D1",
            "rpm_limit": 935,
            "motor_type": "16 cilindros em V",
            "generator": "D22",
            "traction_motors": "D47",
            "allow_multiple_units": True,
            "velocity_max": 104.0000,
            "horsepower_available": 1800,
            "minimum_track_radius": 75400,
            "sigo_numeric_range": "5101-5145 (1 baixa)",
            "nickname": "Cinquentinha, GMinhas, Cascudinhas.",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_SD38-2",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "SD38-2",
            "first_unit_year": 1978,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "motor_builder": "EMD",
            "primary_motor": "EMD 16-645E",
            "rpm_limit": 900,
            "motor_type": "16V",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_SD38M",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "SD38M \"M\" de Modified (Modificada)",
            "first_unit_year": 1967,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "wheelbase": 2.0000,
            "length": 17.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 163.0100,
            "weight_adherent": 163.0100,
            "motor_builder": "GM-EMD",
            "primary_motor": "EMD 645E Aspirado(Sem turbo)",
            "motor_type": "16 cilindros em 45º V (V16)",
            "generator": "D32",
            "traction_motors": "D77",
            "cylinders_size": "230,2 mm (9 1/16 in) x 254,0 mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 96.8000,
            "minimum_track_radius": 23500,
            "sigo_numeric_range": "5101-5144",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_SD40-2",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "SD40-2",
            "first_unit_year": 1972,
            "aar_wheel_arrangement": "C-C",
            "length": 20980.0000,
            "width": 3130.0000,
            "height": 4750.0000,
            "fuel_capacity": "12000 L - 15000 L",
            "motor_builder": "EMD",
            "primary_motor": "EMD 16-645-E3",
            "traction_motors": "6 × D77/78 DC",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_SD70",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "SD70, SD70M, SD70I, SD70MAC, SD70M-2, SD70ACe, SD70ACe/LCi, SD70ACe, SD70ACe-BB, SD70ACe/45, SD70ACe-T4",
            "first_unit_year": 1992,
            "aar_wheel_arrangement": "C-C",
            "motor_builder": "Electro-Motive Diesel (EMD)",
            "primary_motor": "EMD 16-710-G3 EMD 12-1010 para o SD70ACe-T4",
            "motor_type": "V16 V12 para o SD70ACe-T4",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/EMD_SW",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "SW1200",
            "first_unit_year": 1954,
            "aar_wheel_arrangement": "B-B",
            "weight": 112000.0000,
            "weight_per_axle": 28000.0000,
            "primary_motor": "EMD 567C V12",
            "traction_motors": "GM - D77",
            "velocity_max": 100.0000,
            "horsepower_total": 1350,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_1-C%2BC-1_(CPEF)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "GE 1-C+C-1[1]",
            "first_unit_year": 1928,
            "aar_wheel_arrangement": "1-C+C-1",
            "gauge": "Larga",
            "trucks_type": "914 mm",
            "wheel_diameter": 1138.0000,
            "length": 18.0000,
            "weight": 133.0000,
            "allow_multiple_units": True,
            "horsepower_total": 2500,
            "horsepower_available": 2170,
            "nickname": "Quadradona",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_1-C%2BC-1_(EFS)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "1-C+C-1 108/130M",
            "first_unit_year": 1943,
            "aar_wheel_arrangement": "1-C+C-1",
            "gauge": "Métrica",
            "trucks_type": "Barras Soldadas",
            "wheel_diameter": 1118.0000,
            "length": 18.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 130.0000,
            "weight_adherent": 108.0000,
            "sand_capacity": 0.6600,
            "generator": "GE 5GMG-136B1 / YX32A",
            "traction_motors": "G.E.:5 GE 734A1 Westinghouse: 374A",
            "allow_multiple_units": True,
            "horsepower_available": 2000,
            "minimum_track_radius": 80000,
            "brake_system": "14EL",
            "nickname": "Loba e Westinghouse (para as desse fabricante)",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_100T",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "100T[2]",
            "first_unit_year": 1952,
            "aar_wheel_arrangement": "B-B",
            "motor_builder": "Cummins",
            "primary_motor": "NT855L4",
            "generator": "GE 5GT-558",
            "traction_motors": "GE 5GE 763",
            "horsepower_total": 670,
            "horsepower_available": 600,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_2-B%2BB-2",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "GE 2-B+B-2[1]",
            "first_unit_year": 1921,
            "aar_wheel_arrangement": "2-B+B-2",
            "gauge": "Larga",
            "wheel_diameter": 1067.0000,
            "length": 16.0000,
            "weight": 107.0000,
            "horsepower_available": 1450,
            "sigo_numeric_range": "6301 a 6304",
            "nickname": "Quadradinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_2-C%2BC-2",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "GE 2-C+C-2",
            "first_unit_year": 1940,
            "aar_wheel_arrangement": "2-C+C-2",
            "gauge": "Larga",
            "trucks_type": "Barras soldadas",
            "length": 23101.0000,
            "width": 3010.0000,
            "height": 4343.0000,
            "motor_builder": "General Electric e Westinghouse",
            "allow_multiple_units": True,
            "velocity_min": 20.0000,
            "horsepower_total": 3870,
            "minimum_track_radius": 87000,
            "nickname": "V8 ou Escandalosa",
            },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_2-D%2BD-2",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "aar_wheel_arrangement": "2-D+D-2",
            "length": 27080.0000,
            "width": 4390.0000,
            "height": 3230.0000,
            "weight": 247500.0000,
            "motor_builder": "General Electric",
            "motor_type": "GE750 (8)",
            "velocity_max": 109.0000,
            "nickname": "Little Joe (Milwaukee), 800s (South Shore) e Russa (CPEF)",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_244",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "110T",
            "first_unit_year": 1953,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "wheel_diameter": 914.4000,
            "length": 15951.0000,
            "width": 2718.0000,
            "height": 3962.0000,
            "weight": 97000.0000,
            "weight_per_axle": 16200.0000,
            "fuel_capacity": "5300 L",
            "motor_builder": "ALCo",
            "primary_motor": "244 E",
            "motor_type": "12 cilindros em V",
            "traction_motors": "GE-561",
            "allow_multiple_units": True,
            "velocity_max": 96.0000,
            "horsepower_total": 1750,
            "horsepower_available": 1600,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 70000,
            "brake_system": "6SL",
            "sigo_numeric_range": "2487-2499",
            "nickname": "Híbridas",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_25T",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "B 50/50",
            "first_unit_year": 1946,
            "aar_wheel_arrangement": "B",
            "gauge": "Métrica",
            "wheel_diameter": 838.2000,
            "wheelbase": 1.0000,
            "length": 5.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 23.1000,
            "weight_per_axle": 11.5500,
            "fuel_capacity": "284 L",
            "lubricant_oil_capacity": 32,
            "cooling_fluid_capacity": 64,
            "motor_builder": "Cummins – U.S.A. (Original)  FNM",
            "primary_motor": "H81 -600 (Original)  ALFA ROMEU Série 180 (alterado na década de 70) (RVPSC)  Cummins (outras)",
            "rpm_limit": 1850,
            "generator": "GT-1503-X1",
            "traction_motors": "GE 733 - FI",
            "cylinders_size": "125,0 mm x 150,0 mm",
            "allow_multiple_units": False,
            "velocity_max": 32.0000,
            "traction_effort": 6,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 12200,
            "brake_system": "AS-2",
            "sigo_numeric_range": "0505-0510 (RFFSA)",
            "nickname": "Bitruca / Bitruquinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_47T",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "47T[1]",
            "first_unit_year": 1947,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "motor_builder": "Cummins",
            "primary_motor": "Cu D17000",
            "horsepower_total": 380,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_70T",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "70T[1]",
            "first_unit_year": 1947,
            "aar_wheel_arrangement": "B-B (1,6m) ou C-C (1,0m)",
            "motor_builder": "Cooper-Bressemer",
            "primary_motor": "FWL 6T",
            "horsepower_total": 600,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_88T",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "88T[1]",
            "first_unit_year": 1956,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_AC44i",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "AC44i",
            "first_unit_year": 2008,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "trucks_type": "Hi-AD C-C (corrente alternada)",
            "length": 22.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 198.0000,
            "weight_per_axle": 33.0000,
            "motor_builder": "GE",
            "motor_type": "Combustão interna",
            "allow_multiple_units": True,
            "velocity_max": 113.0000,
            "horsepower_total": 4500,
            "horsepower_available": 4380,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_B%2BB_(CPEF)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "GE B+B[1]",
            "first_unit_year": 1921,
            "aar_wheel_arrangement": "B+B",
            "gauge": "Larga",
            "wheel_diameter": 1066.0000,
            "length": 11.0000,
            "weight": 88.9000,
            "horsepower_available": 1450,
            "sigo_numeric_range": "6401 a 6408",
            "nickname": "Quadradinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_B-B_(CPEF_-_Baratinha)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "B-B",
            "first_unit_year": 1924,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
            "wheel_diameter": 1016.0000,
            "weight": 55.5000,
            "horsepower_total": 662,
            "horsepower_available": 460,
            "sigo_numeric_range": "6501-6518",
            "nickname": "Baratinha (1ª série) Baratona (2ª série)",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_B-B_(EFS)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "name": "Série 2100",
            "first_unit_year": 1964,
            "gauge": "Métrica",
            "trucks_type": "fundidos",
            "wheel_diameter": 1118.0000,
            "wheelbase": 6501.0000,
            "length": 13942.0000,
            "width": 3047.0000,
            "height": 4254.0000,
            "weight": 72800.0000,
            "weight_per_axle": 18200.0000,
            "weight_adherent": 72800.0000,
            "motor_builder": "General Electric",
            "velocity_max": 90.0000,
            "minimum_track_radius": 85000,
            "brake_system": "F-4",
            "sigo_numeric_range": "912100",
            "nickname": "Mini-Saia",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_BB33",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "BB33-7MP",
            "first_unit_year": 1981,
            "aar_wheel_arrangement": "C-C/B-B+B-B",
            "gauge": "Métrica",
            "weight": 180.0000,
            "weight_per_axle": 22.5000,
            "primary_motor": "16-FDL7B",
            "traction_motors": "ELETROFAN EF570",
            "velocity_max": 80.0000,
            "horsepower_total": 3500,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_BB40-9M",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "BB40-9M[1]",
            "first_unit_year": 1995,
            "aar_wheel_arrangement": "B-B+B-B",
            "gauge": "Métrica",
            "motor_builder": "GE",
            "primary_motor": "FDL 16",
            "horsepower_total": 4000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_BB40-9WM",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "Dash 9-40BBW [1]",
            "first_unit_year": 1997,
            "aar_wheel_arrangement": "B+B-B+B",
            "gauge": "Métrica",
            "motor_builder": "GE Transportation",
            "primary_motor": "FDL 16",
            "horsepower_total": 4000,
            "sigo_numeric_range": "EFVM: 1113-1311 a partir de 2009: VLI: 6020-6191 e 8667-8684 ALL: 8300-8315 Brado: 9577-9579",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C-C_(CPEF)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "first_unit_year": 1964,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "wheel_diameter": 1.0000,
            "wheelbase": 2.0000,
            "length": 18.0000,
            "width": 2997.0000,
            "height": 4388.0000,
            "weight": 144.0000,
            "weight_per_axle": 24.0000,
            "weight_adherent": 144.0000,
            "motor_builder": "General Electric",
            "generator": "2x GMG136",
            "traction_motors": "6x G.E. 729",
            "allow_multiple_units": True,
            "velocity_max": 134.0000,
            "horsepower_total": 5250,
            "horsepower_available": 4450,
            "traction_effort": 22,
            "sigo_numeric_range": "6351-6360",
            "nickname": "Vandeca, Vanderleia",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C-C_(RFFSA)",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "GE",
            "first_unit_year": 1962,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "wheel_diameter": 1168.4000,
            "wheelbase": 2.0000,
            "length": 15.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 123.0000,
            "weight_per_axle": 20.5000,
            "weight_adherent": 123.0000,
            "rpm_limit": 859,
            "traction_motors": "G.E. 729",
            "allow_multiple_units": True,
            "velocity_max": 117.0000,
            "horsepower_available": 4400,
            "minimum_track_radius": 100000,
            "brake_system": "26L",
            "sigo_numeric_range": "2151-2156 / 9080-9085",
            "nickname": "Charutão ou Carioquinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C22-7i",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "c22-7i",
            "first_unit_year": 1999,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "length": 18.0000,
            "weight": 117.6000,
            "weight_per_axle": 19.6000,
            "motor_builder": "GE",
            "primary_motor": "7FDL12",
            "rpm_limit": 1000,
            "motor_type": "Combustão interna",
            "cylinders_size": "228,6 mm x 266,7 mm",
            "allow_multiple_units": True,
            "horsepower_total": 2400,
            "traction_effort": 36,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C30-7",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "C30-7",
            "first_unit_year": 1976,
            "aar_wheel_arrangement": "C-C",
            "length": 20.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 172.0000,
            "weight_per_axle": 28.6600,
            "fuel_capacity": "13900 L - 15000 L",
            "primary_motor": "16-FDL7B // 12-FDL7B",
            "traction_motors": "GM - EMD D-31",
            "velocity_max": 113.0000,
            "horsepower_total": 3350,
            "horsepower_available": 3000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C32-8",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "C32-8",
            "first_unit_year": 1984,
            "aar_wheel_arrangement": "C-C",
            "primary_motor": "GE 7FDL-12",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C36ME",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE C30-7 – Modernizada",
            "first_unit_year": 1977,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "length": 20.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 180.0000,
            "weight_per_axle": 30.0000,
            "motor_builder": "GE",
            "motor_type": "7 FDL",
            "horsepower_total": 3600,
            "sigo_numeric_range": "3801-3809 e 3860-3885",
            "nickname": "Raiovack",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C40-8",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "C40-8[1]",
            "first_unit_year": 1989,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "length": 21539.0000,
            "width": 3137.0000,
            "height": 4686.0000,
            "weight": 177600.0000,
            "weight_per_axle": 29600.0000,
            "motor_builder": "GE",
            "primary_motor": "7 FDL 16",
            "velocity_max": 112.0000,
            "horsepower_total": 4000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_C44-9WM",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "C44-9WM",
            "first_unit_year": 1998,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "trucks_type": "HiAd",
            "wheel_diameter": 1.0000,
            "length": 22.0000,
            "width": 3.0000,
            "height": 4.0000,
            "weight": 193.0000,
            "weight_per_axle": 32.5000,
            "weight_adherent": 193.0000,
            "fuel_capacity": "18900 L",
            "primary_motor": "GE 7FDL-16",
            "generator": "5GMG-197",
            "traction_motors": "5GE – 752",
            "horsepower_total": 4500,
            "horsepower_available": 4380,
            "sigo_numeric_range": "Série 800 EFC, Série 9000 ALL",
            "nickname": "Dash9, Dash Nine",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_ES43BBi",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE ES43BBi",
            "first_unit_year": 2015,
            "aar_wheel_arrangement": "B+B-B+B",
            "gauge": "Métrica",
            "trucks_type": "AC (corrente alternada)",
            "length": 24700.0000,
            "weight": 196.0000,
            "fuel_capacity": "14400 L",
            "motor_builder": "GE",
            "primary_motor": "GEVO-12",
            "motor_type": "Combustão interna",
            "allow_multiple_units": True,
            "velocity_max": 113.0000,
            "horsepower_total": 4300,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_ES58ACi",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE ES58ACi",
            "first_unit_year": 2009,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Larga",
            "primary_motor": "GEVO",
            "horsepower_total": 6000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_SL100",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "SL100[1]",
            "first_unit_year": 1998,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "motor_builder": "Cummins",
            "primary_motor": "CumKTA 1150L",
            "horsepower_total": 1000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_SL65T",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "SL65T[1]",
            "first_unit_year": 1998,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
            "motor_builder": "Cummins",
            "primary_motor": "Cum. NT 855L4",
            "horsepower_total": 600,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U12B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U12B (B-B160/160-4GE761)",
            "first_unit_year": 1957,
            "aar_wheel_arrangement": "B-B",
            "wheel_diameter": 914.4000,
            "wheelbase": 2.0000,
            "length": 14.0000,
            "width": 2.0000,
            "height": 3.0000,
            "motor_builder": "Cooper Bessemer",
            "primary_motor": "FVBL-8T[3]",
            "generator": "5GT-581-C3",
            "traction_motors": "5GE-761-A3",
            "allow_multiple_units": True,
            "horsepower_total": 1320,
            "horsepower_available": 1200,
            "brake_system": "6SL",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U12C",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U12C",
            "first_unit_year": 1956,
            "aar_wheel_arrangement": "C-C",
            "wheel_diameter": 914.4000,
            "wheelbase": 2.0000,
            "length": 14.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 70000.0000,
            "motor_builder": "Cooper Bessemer",
            "primary_motor": "FVBL-8T[2]",
            "generator": "5GT-581-C3",
            "traction_motors": "5GE-761-A3",
            "allow_multiple_units": True,
            "horsepower_total": 1320,
            "horsepower_available": 1200,
            "brake_system": "6SL",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U13B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U13B",
            "first_unit_year": 1959,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "wheel_diameter": 914.4000,
            "length": 15144.0000,
            "width": 2743.0000,
            "height": 3664.0000,
            "weight": 70000.0000,
            "weight_per_axle": 17500.0000,
            "weight_adherent": 17500.0000,
            "fuel_capacity": "3028 L",
            "motor_builder": "GE-Cooper Bessemer",
            "primary_motor": "7 FDL 8",
            "motor_type": "V",
            "generator": "5GT-581-C3",
            "traction_motors": "5GE-761-A3",
            "allow_multiple_units": True,
            "velocity_max": 97.0000,
            "horsepower_total": 1420,
            "horsepower_available": 1300,
            "brake_system": "6SL",
            "sigo_numeric_range": "2401-2445",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U18C",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U18C",
            "first_unit_year": 1958,
            "aar_wheel_arrangement": "C-CA1A-A1A1-C-C-1",
            "gauge": "Métrica",
            "weight": 92500.0000,
            "weight_per_axle": 15400.0000,
            "fuel_capacity": "3407 L",
            "motor_builder": "Copper-Bressemer",
            "primary_motor": "FVBL 12T",
            "motor_type": "12 cilindros em V",
            "allow_multiple_units": True,
            "horsepower_total": 1980,
            "horsepower_available": 1800,
            "brake_system": "6-SL-AV-1",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U20C",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "U20C",
            "first_unit_year": 1968,
            "aar_wheel_arrangement": "C-C",
            "trucks_type": "AAR",
            "wheel_diameter": 914.4000,
            "length": 15.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 94.4940,
            "weight_per_axle": 15.7500,
            "weight_adherent": 94.4940,
            "fuel_capacity": "6000 L",
            "lubricant_oil_capacity": 1,
            "cooling_fluid_capacity": 851,
            "sand_capacity": 0.5100,
            "motor_builder": "GE",
            "primary_motor": "7FDL12",
            "rpm_limit": 1000,
            "motor_type": "Combustão interna",
            "traction_motors": "5GE761 A6",
            "cylinders_size": "228,6 mm x 266,7 mm",
            "allow_multiple_units": True,
            "velocity_max": 120.0000,
            "velocity_min": 20.0000,
            "horsepower_total": 2150,
            "horsepower_available": 1990,
            "traction_effort": 22,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 95000,
            "brake_system": "28L-AV-1",
            "nickname": "Namibiana, Cachorrona",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U22C",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U22C",
            "first_unit_year": 1985,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "wheel_diameter": 914.4000,
            "length": 17983.0000,
            "width": 2795.0000,
            "weight": 120000.0000,
            "weight_per_axle": 20000.0000,
            "fuel_capacity": "6770 L",
            "motor_builder": "GE",
            "primary_motor": "7FDL12",
            "motor_type": "12 cilindros em V",
            "traction_motors": "5GE-761-A20",
            "allow_multiple_units": True,
            "horsepower_total": 2408,
            "horsepower_available": 2200,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 63000,
            "brake_system": "26L",
            "sigo_numeric_range": "2801-2810",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U23C",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "U23C",
            "first_unit_year": 1972,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "wheel_diameter": 1016.0000,
            "length": 20.0000,
            "width": 3.0000,
            "height": 4.0000,
            "fuel_capacity": "15000 L",
            "motor_builder": "GE",
            "primary_motor": "7FDL12 TURBO",
            "rpm_limit": 1050,
            "motor_type": "Combustão interna",
            "generator": "GT596 CC",
            "traction_motors": "752B",
            "cylinders_size": "230,2 mm (9 1/16 in) x 266,7 mm (10 1/2 in)",
            "allow_multiple_units": True,
            "velocity_max": 103.0000,
            "horsepower_total": 2475,
            "horsepower_available": 2250,
            "traction_effort": 38,
            "adhesion_factor": 0.2500,
            "brake_system": "26L",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U26C",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "U26C",
            "first_unit_year": 1981,
            "aar_wheel_arrangement": "C-C",
            "gauge": "Métrica",
            "wheel_diameter": 914.4000,
            "length": 16.0000,
            "width": 3.0000,
            "height": 3.0000,
            "weight": 120.0000,
            "weight_per_axle": 20.0000,
            "weight_adherent": 120.0000,
            "fuel_capacity": "7500 L",
            "motor_builder": "GE",
            "primary_motor": "7FDL12 TURBO",
            "rpm_limit": 1050,
            "motor_type": "Combustão interna",
            "traction_motors": "761A17",
            "cylinders_size": "230,2 mm (9 1/16 in) x 266,7 mm (10 1/2 in)",
            "allow_multiple_units": True,
            "velocity_max": 103.0000,
            "velocity_min": 20.0000,
            "horsepower_total": 2850,
            "horsepower_available": 2700,
            "traction_effort": 24,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 72000,
            "brake_system": "26L",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U50",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U50",
            "first_unit_year": 1963,
            "aar_wheel_arrangement": "B+B-B+B",
            "trucks_type": "\"B\"",
            "motor_builder": "GE",
            "motor_type": "2 motores GE FDL-16",
            "horsepower_total": 5000,
            "nickname": "Baby Hueys",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U5B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "U5B",
            "first_unit_year": 1961,
            "aar_wheel_arrangement": "B-B",
            "wheel_diameter": 914.4000,
            "wheelbase": 2.0000,
            "length": 11.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 49.8950,
            "weight_per_axle": 12.4700,
            "weight_adherent": 49.8950,
            "fuel_capacity": "1514 L",
            "lubricant_oil_capacity": 272,
            "sand_capacity": 0.3400,
            "motor_builder": "Caterpillar",
            "primary_motor": "D-379",
            "rpm_limit": 1300,
            "motor_type": "Combustão interna",
            "generator": "GE 5GMG-146E1",
            "traction_motors": "5GE – 761 A1",
            "cylinders_size": "158,8 mm (6 1/4 in) x 203,2 mm (8 in)",
            "allow_multiple_units": False,
            "velocity_max": 64.0000,
            "velocity_min": 20.0000,
            "horsepower_total": 600,
            "horsepower_available": 540,
            "traction_effort": 9,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 22900,
            "brake_system": "6SL",
            "sigo_numeric_range": "Série 2000 (2001-2088)  e 3000 (3001-3020)",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U6B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "U6B",
            "first_unit_year": 1961,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
            "wheel_diameter": 914.4000,
            "wheelbase": 2.0000,
            "length": 11.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 53.1000,
            "weight_per_axle": 18.8350,
            "weight_adherent": 53.1000,
            "fuel_capacity": "1514 L",
            "motor_builder": "Caterpillar",
            "primary_motor": "Cat D 379",
            "generator": "GT601",
            "traction_motors": "7G1A5",
            "cylinders_size": "158,8 mm (6 1/4 in) x 203,2 mm (8 in)",
            "velocity_max": 64.0000,
            "horsepower_total": 700,
            "traction_effort": 15,
            "minimum_track_radius": 22900,
            "nickname": "Caterpillar",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U8B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "GE U8B",
            "first_unit_year": 1960,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "wheel_diameter": 914.4000,
            "length": 11380.0000,
            "width": 2743.0000,
            "height": 3658.0000,
            "weight": 54500.0000,
            "weight_per_axle": 13625.0000,
            "fuel_capacity": "1514 L",
            "motor_builder": "Caterpillar",
            "primary_motor": "D398",
            "motor_type": "V Superalimentado",
            "generator": "5GT-601-A1",
            "traction_motors": "5GE-761-A1",
            "allow_multiple_units": True,
            "velocity_max": 96.0000,
            "horsepower_total": 900,
            "horsepower_available": 810,
            "brake_system": "6SL",
            "sigo_numeric_range": "2131-2190",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_U9B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "U9",
            "first_unit_year": 1957,
            "aar_wheel_arrangement": "B-B (Brasil) ou C-C (Chile)",
            "motor_builder": "Cooper-Bressemer",
            "primary_motor": "CB. FWL 6T",
            "horsepower_total": 1060,
            "sigo_numeric_range": "RFFSA 2197 a 2199",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GE_UM10B",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "GE",
            "name": "UM10B[1]",
            "first_unit_year": 1961,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Larga",
            "wheel_diameter": 1.0000,
            "motor_builder": "Caterpillar",
            "primary_motor": "Cat D 398",
            "generator": "5GT-601",
            "traction_motors": "5GE 752",
            "horsepower_total": 1050,
            "horsepower_available": 950,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GMD_B12",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "B12",
            "first_unit_year": 1953,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Flexcoil",
            "wheel_diameter": 1016.0000,
            "wheelbase": 2.0000,
            "length": 13.0000,
            "width": 2.0000,
            "height": 3.0000,
            "weight": 68.0000,
            "weight_per_axle": 17.0000,
            "weight_adherent": 68.0000,
            "fuel_capacity": "4540 L",
            "lubricant_oil_capacity": 625,
            "sand_capacity": 0.3400,
            "motor_builder": "EMD",
            "primary_motor": "EMD 12-567B",
            "rpm_limit": 800,
            "motor_type": "Combustão interna",
            "motor_capacity": "9.290cc³ x 12",
            "generator": "D15-E",
            "traction_motors": "D19",
            "cylinders_size": "215,9 mm (8 1/2 in) x 254,0mm (10 in)",
            "allow_multiple_units": True,
            "velocity_max": 97.0000,
            "velocity_min": 16.0000,
            "horsepower_available": 1015,
            "traction_effort": 14,
            "adhesion_factor": 0.2500,
            "minimum_track_radius": 58820,
            "brake_system": "6SL",
            "sigo_numeric_range": "4091 a 4099",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/GMD_GMDH-1",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "EMD",
            "name": "GMD-1",
            "first_unit_year": 1956,
            "aar_wheel_arrangement": "B-B",
            "weight": 54400.0000,
            "weight_per_axle": 13600.0000,
            "fuel_capacity": "1590 L",
            "primary_motor": "Detroid Diesel modêlo 60 e 71",
            "velocity_max": 64.0000,
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/LEW_DE_I_PA",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "LEW",
            "name": "DE-I-PA",
            "first_unit_year": 1967,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Apoio Elástico",
            "wheel_diameter": 1050.0000,
            "wheelbase": 7700.0000,
            "length": 14660.0000,
            "width": 3000.0000,
            "height": 3900.0000,
            "weight": 74000.0000,
            "weight_per_axle": 18500.0000,
            "fuel_capacity": "2900 L",
            "lubricant_oil_capacity": 130,
            "cooling_fluid_capacity": 620,
            "motor_builder": "SACM",
            "primary_motor": "MGO V12 BSHR",
            "rpm_limit": 1500,
            "motor_type": "12 cilindros em “V”",
            "generator": "GBG 0609-150A",
            "traction_motors": "GMFB 0609-41",
            "cylinders_size": "175 mm x 180 mm",
            "allow_multiple_units": True,
            "horsepower_total": 1050,
            "minimum_track_radius": 90000,
            "sigo_numeric_range": "7761 a 7796",
            "nickname": "Alemãzinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/LEW_DE_II_S",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "LEW",
            "name": "DE-II-S",
            "first_unit_year": 1968,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Soldado",
            "wheel_diameter": 1050.0000,
            "wheelbase": 7700.0000,
            "length": 14500.0000,
            "width": 3000.0000,
            "height": 3900.0000,
            "weight": 70000.0000,
            "weight_per_axle": 17500.0000,
            "fuel_capacity": "2900 L",
            "lubricant_oil_capacity": 130,
            "cooling_fluid_capacity": 620,
            "motor_builder": "SACM",
            "primary_motor": "MGO V12 BSHR",
            "rpm_limit": 1500,
            "motor_type": "12 cilindros em “V”",
            "generator": "GBG 0909-150A",
            "traction_motors": "GMFB 0609-41",
            "cylinders_size": "175 mm x 180 mm",
            "allow_multiple_units": True,
            "horsepower_total": 1050,
            "minimum_track_radius": 90000,
            "sigo_numeric_range": "3701 a 3730",
            "nickname": "Alemãzinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/LEW_DE_III_M",
            "prime_mover_type": "DIESEL_ELECTRIC",
            "manufacturer": "LEW",
            "name": "DE-III-M",
            "first_unit_year": 1968,
            "aar_wheel_arrangement": "B-B",
            "gauge": "Métrica",
            "trucks_type": "Soldado",
            "wheel_diameter": 1050.0000,
            "wheelbase": 7700.0000,
            "length": 14500.0000,
            "width": 3000.0000,
            "height": 3900.0000,
            "weight": 70000.0000,
            "weight_per_axle": 17500.0000,
            "fuel_capacity": "2900 L",
            "lubricant_oil_capacity": 160,
            "cooling_fluid_capacity": 720,
            "motor_builder": "SACM",
            "primary_motor": "MGO V16 BSHR",
            "rpm_limit": 1500,
            "motor_type": "16 cilindros em “V”",
            "generator": "GBG 0609-150A",
            "traction_motors": "GMFB 0609-41",
            "cylinders_size": "175 mm x 180 mm",
            "allow_multiple_units": True,
            "horsepower_total": 1400,
            "minimum_track_radius": 90000,
            "sigo_numeric_range": "3751 a 3767",
            "nickname": "Alemãzinha",
        },
        {
            "wikipedia_url": "https://pt.wikipedia.org/wiki/Winterthur-BBC_1-D-1",
            "prime_mover_type": "ELECTRIC",
            "manufacturer": "Winterthur",
            "first_unit_year": 1929,
            "aar_wheel_arrangement": "1-D-1",
            "gauge": "Larga",
            "wheel_diameter": 1600.0000,
            "length": 16192.0000,
            "weight": 123400.0000,
            "velocity_max": 105.0000,
            "horsepower_available": 2520,
        },
    ])
