# Generated by Django 3.0.7 on 2020-06-21 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infotrem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackGauge',
            fields=[
                ('gauge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.FloatField(unique=True, verbose_name='Size of the gauge in meters')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='track_gauge',
        ),
        migrations.CreateModel(
            name='LocationTrackGauge',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infotrem.Location')),
                ('track_gauge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infotrem.TrackGauge')),
            ],
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='gauge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infotrem.TrackGauge'),
        ),
        migrations.AlterField(
            model_name='rollingstockfreightcargrossweighttype',
            name='gauge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infotrem.TrackGauge'),
        ),
        migrations.DeleteModel(
            name='TrackGaugeConfiguration',
        ),
    ]
