# Generated by Django 3.2.15 on 2022-09-18 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220918_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Record primary key (UUID v4)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Record last update timestamp')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Vote value')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informationvote_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user')),
                ('information', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.information')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informationvote_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='informationvote',
            constraint=models.UniqueConstraint(fields=('information', 'created_by'), name='Only one vote per user on each information'),
        ),
    ]
