# Generated by Django 3.2.15 on 2022-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220918_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationeffect',
            name='new_value',
            field=models.TextField(max_length=1024, null=True, verbose_name='The new value of the field (after the information is accepted)'),
        ),
    ]
