# Generated by Django 3.2.15 on 2022-09-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220921_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='album',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='album_comments', to='core.album', verbose_name='The album associated with the comment'),
        ),
    ]
