# Generated by Django 3.2.15 on 2022-09-21 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_albumcomment_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Record primary key (UUID v4)')),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/time when the information was liked')),
                ('information', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.information', verbose_name='Information object which received the like')),
                ('liked_by', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='information_like_creator', to=settings.AUTH_USER_MODEL, verbose_name='User who liked the information')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
