# Generated by Django 4.1.1 on 2022-09-25 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_informationlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='album',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='albumcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='albumcomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='albummedia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='albummedia',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='companypaintscheme',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_paint_schemes', to='core.company'),
        ),
        migrations.AlterField(
            model_name='companypaintscheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='companypaintscheme',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='companypaintschemeinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='companypaintschemeinformation',
            name='paint_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_paint_schemes_information', to='core.companypaintscheme', verbose_name='Paint scheme which holds the information'),
        ),
        migrations.AlterField(
            model_name='companypaintschemeinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='freightcar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='freightcar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='information',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='information',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='informationeffect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='informationeffect',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='informationvote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='informationvote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='locationinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='locationinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='locationpath',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='locationpath',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='locationtrackgauge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='locationtrackgauge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='locomotivedesign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='locomotivedesign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='locomotivedesigngauge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='locomotivedesigngauge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='media',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediacomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediacomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediadocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediadocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediaimagesized',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediaimagesized',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediareview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediareview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediarollingstock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediarollingstock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='nonrevenuecar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='nonrevenuecar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='passengercar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='passengercar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='path',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='path',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='pathpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='pathpoint',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='rollingstockinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='rollingstockinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='routeinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='routeinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='routesectioninformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='routesectioninformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='routesectionlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='routesectionlocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='routesectionlocationkilometer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='routesectionlocationkilometer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='routesectionpath',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='routesectionpath',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
        migrations.AlterField(
            model_name='sigoseriesinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Record creation user'),
        ),
        migrations.AlterField(
            model_name='sigoseriesinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='Record last update user'),
        ),
    ]
